# Generated by Django 6.0.5 on 2026-05-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='motivation_letter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
